sudo: false

language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "nightly"
  - "pypy"
  - "pypy3"

env:
  matrix:
    - COVERAGE=cover,codecov
    - COVERAGE=nocov
  
before_install:
  - ls -la ~/virtualenv
  - export TOXENV=${TRAVIS_PYTHON_VERSION/[0-9].[0-9]/py${TRAVIS_PYTHON_VERSION/.}}
  - cat "$BASH_SOURCE"
  - env

install:
  - pip list
  - virtualenv --version
  - pip install tox pytest-travis-fold
  - pip list
  - virtualenv --version
  - easy_install --version
  - pip --version
  - tox --version
  - alias tox="echo ${ANSI_GREEN}Running tox for TOXENV=$TOXENV${ANSI_RESET}; tox"

script:
  - tox -v || true

cache:
  directories:
    - $HOME/.cache/pip/http

notifications:
  email:
    on_success: never
    on_failure: never

