sudo: false

language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5-dev"
  - "nightly"
  - "pypy"
  - "pypy3"

announce: echo FUUUUUUU

install: pip install --upgrade pip setuptools
after_install: pip --version

script:
  - pip list

cache:
  directories:
    - $HOME/.cache/pip/http
