sudo: false

language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5-dev"
  - "nightly"
  - "pypy"
  - "pypy3"

install: pip install --upgrade pip setuptools
script:
  - pip list
  - du -h $HOME/.cache/pip

before_cache:
  - ls -la $HOME/.cache/pip/log
  - rm -f  $HOME/.cache/pip/log/debug.log
  - ls -la $HOME/.cache/pip/log
cache:
  directories:
    - $HOME/.cache/pip
