sudo: false

language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5-dev"
  - "nightly"
  - "pypy"
  - "pypy3"

before_install:
  - cat "$BASH_SOURCE"

install:
  - pip install --upgrade pip setuptools
  - pip --version
  - pip list

script:
  - source test.sh

cache:
  directories:
    - $HOME/.cache/pip/http
