sudo: false

language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "nightly"
  - "pypy"
  - "pypy3"

env:
  global:
    - TOXENV="${TRAVIS_PYTHON_VERSION/[0-9].[0-9]/py${TRAVIS_PYTHON_VERSION/.}}"
  
before_install:
  - cat "$BASH_SOURCE"

install:
  - pip install tox pytest-travis-fold

script:
  - env
  - tox -v

cache:
  directories:
    - $HOME/.cache/pip/http

notifications:
  email:
    on_success: never
    on_failure: never

