sudo: false

language: python
python:
  - "2.7"
  - "3.4"

env:
  matrix:
    - COVERAGE=cover,codecov
    - COVERAGE=nocov
  
before_install:
  - python --version
  - cat "$BASH_SOURCE"

install:
  - pip list
  - virtualenv --version
  - pip install tox pytest-travis-fold
  - pip list
  - virtualenv --version
  - easy_install --version
  - pip --version
  - tox --version
before_script:
  - export TOXENV=${TRAVIS_PYTHON_VERSION/[0-9].[0-9]/py${TRAVIS_PYTHON_VERSION/.}}
  - env
  - |
    function tox()
      { announce "Running tox in TOXENV=$TOXENV"; env tox; }
    function announce()
      { echo -e "$ANSI_GREEN$@${ANSI_RESET}"; }
script:
  - tox -v

cache:
  directories:
    - $HOME/.cache/pip/http

notifications:
  email:
    on_success: never
    on_failure: never

