sudo: false

language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "nightly"
  - "pypy"
  - "pypy3"

before_install:
  - cat "$BASH_SOURCE"

install:
  - pip install --upgrade pip setuptools
  - pip --version
  - pip install pytest-catchlog pytest-travis-fold
  - pip list

script:
  - py.test

cache:
  directories:
    - $HOME/.cache/pip/http
